# Generated by Django 4.1.5 on 2023-01-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='Halal_Category',
            field=models.CharField(default='Yes', max_length=10),
            preserve_default=False,
        ),
    ]
