# Generated by Django 4.1.5 on 2023-01-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Halal',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
